### ISSUE TITLE
label extension

### ISSUE THREAD

**Issue by matthewhanson** [stac-extensions/stac-extensions.github.io#11]
label extension has been updated and already published, needs to be reviewed.

https://github.com/stac-extensions/label

**Comment by m-mohr** [comment]
Going to review

**Comment by m-mohr** [comment]
I've reviewed the labels extension, applied some changes (esp. schemas) and opened an issue: https://github.com/stac-extensions/label/issues/4

**Comment by matthewhanson** [comment]
Published, the new issue can be added for a 1.0.1 release.
