### ISSUE TITLE
timestamps extension

### ISSUE THREAD

**Issue by matthewhanson** [stac-extensions/stac-extensions.github.io#13]
timestamps extension has been updated and already published. It needs review

https://github.com/stac-extensions/timestamps

**Comment by m-mohr** [comment]
Review is done

**Comment by matthewhanson** [comment]
Looks like it will need to be republished since there's JSON schema updates since the initial release.  @jbants if all looks good now can you republish then you can close this ticket.

**Comment by m-mohr** [comment]
I've cleaned the release anyway, so we can start fresh with 1.0.0 for this one.

**Comment by m-mohr** [comment]
I cleaned-up the releases, updated the changelog and made the release.
