### ISSUE TITLE
Dynamically generate STAC Extensions table

### ISSUE THREAD

**Issue by matthewhanson** [stac-extensions/stac-extensions.github.io#26]
Keeping the list up to date with the info in the individual repos is difficult.

This could be generated dynamically with some javascript and the github API.  Need to grab the README from each and parse to fill in the table columns

**Comment by m-mohr** [comment]
What about extensions that are not part of this organization?

**Comment by matthewhanson** [comment]
They can be a separate table and could be manually updated.  But a dynamically created table for all extensions provided in the stac-extensions repo would ensure that the summary table isn't out of date most of the time.

**Comment by m-mohr** [comment]
Done
